nix:
  enable: false
  packages: [zlib zlib.dev]

flags:
  gitit:
    plugins: true
packages:
- '.'
extra-deps:
- pandoc-types-1.21
- pandoc-2.10
- pandoc-citeproc-0.17.0.1
- texmath-0.12.0.2
- haddock-library-1.9.0
- skylighting-0.8.5
- skylighting-core-0.8.5
- regex-pcre-builtin-0.95.1.2.8.43
- regex-base-0.94.0.0
- doclayout-0.3
- emojis-0.1
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- HsYAML-0.2.1.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.8.2
- ConfigFile-1.1.4
- filestore-0.6.4
- happstack-server-7.6.0
- json-0.10
- MissingH-1.4.3.0
- recaptcha-0.1.0.4

allow-newer: true
resolver: lts-15.10
