name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ghc: '8.0.2'
            cabal: '2.4'
          - ghc: '8.2.2'
            cabal: '2.4'
          - ghc: '8.4.4'
            cabal: '2.4'
          - ghc: '8.6.5'
            cabal: '3.2'
          - ghc: '8.8.3'
            cabal: '3.2'
          - ghc: '8.10.1'
            cabal: '3.2'
    steps:
    - uses: actions/checkout@v1
    # need to install older cabal/ghc versions from ppa repository

    - name: Install recent cabal/ghc
      run: |
         if [[ ! -d /opt/ghc/${{ matrix.versions.ghc }} ]]
         then
           sudo add-apt-repository ppa:hvr/ghc
           sudo apt-get update
           sudo apt-get install ghc-${{ matrix.versions.ghc }} cabal-install-${{ matrix.versions.cabal }}
         fi
         # Use a GitHub workflow command to add folders to PATH.
         echo "::add-path::/opt/ghc/${{ matrix.versions.ghc }}/bin"
         echo "::add-path::/opt/cabal/${{ matrix.versions.cabal }}/bin"

    - name: Install dependencies
      run: |
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests --disable-optimization -fexecutable all
    - name: Build and test
      run: |
          export PATH=/opt/cabal/${{ matrix.versions.cabal }}/bin:/opt/ghc/${{ matrix.versions.ghc }}/bin:$PATH
          cabal v2-build --enable-tests --disable-optimization -fexecutable all

  macos:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      run: |
          curl -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz -o stack.tar.gz
          tar xzvf stack.tar.gz --strip-components=1 'stack*/stack'
    - name: Install dependencies
      run: |
          ./stack update
          ./stack test --dependencies-only --fast
    - name: Build and test
      run: |
          ./stack install --fast --test --haddock --no-haddock-deps
